### ISSUE TITLE
Vector of vectors not store de value

### ISSUE THREAD

**Issue by jrsanchezalcala** [janelia-arduino/Vector#1]
I,m trying to store Vector<String> in Vector and when i do in first loop all values are printed ok but in the second this values are not printed . Do you know why?

```
#include "ESP8266WiFi.h"
#include <Vector.h>
void setup() {
    Serial.begin(115200);
  // put your setup code here, to run once:
 // setup
  WiFi.mode(WIFI_STA);
  WiFi.disconnect();
  delay(100);

  Serial.println("Setup done");
  // scan

  Serial.println("scan start");

  // WiFi.scanNetworks will return the number of networks found
  int n = WiFi.scanNetworks();
  Serial.println("scan done");
  if (n == 0) {
    Serial.println("no networks found");

  } else {
    Serial.print(n);
    Serial.println(" networks found");

    Vector< Vector<String> >  result;
    Vector<String> r[20];
    result.setStorage(r);
    for (int i = 0; i < n; i++) {
      String s [3];
      Vector<String> v;
      v.setStorage(s);
     
      // Print SSID and RSSI for each network found
      /**Serial.println(i + 1);
      Serial.print(": ");
      Serial.print(WiFi.SSID(i));
      Serial.print(" (");
      Serial.print(WiFi.RSSI(i));
      Serial.print(")");
      Serial.println((WiFi.encryptionType(i) == ENC_TYPE_NONE) ? " " : "*");**/
      v.push_back( WiFi.SSID(i));
      result.push_back(v);
      Serial.print("result[i][0] : ");
      Serial.println(result[i][0]);
      //result[i][1] = static_cast<char*>WiFi.RSSI(i);
      //result[i][2] = static_cast<char*>WiFi.encryptionType(i);

      delay(10);
    }
     Serial.print("Second Loop ");
    Serial.println(result.size());
    for(int a = 0; a < result.size(); a++){
          Serial.println(result[a][0]);
     }
  }
}

void loop() {
  // put your main code here, to run repeatedly:
delay(100000);
}
```

**Comment by peterpolidoro** [comment]
Hi. That is probably not working because your storage is a local variable that is falling out of scope.

I use Vector when I am trying to avoid dynamic memory on the heap. Using heap memory on microprocessors can have issues. String uses heap memory so it does not really make sense to use this Vector library if you do not mind using heap memory. You could just use a heap allocated Vector library instead.

This Vector library is just a wrapper around a c-style array. You could use a 2D c-style array of Strings for your program to easily do what you want instead of using this library.

You could get this library to work if you really want stack allocated storage with vector methods. I might need to make some modifications to make it work well with multidimensional arrays. I will play around with it when I get a chance. In the mean time you might be able to get it to work if you move your storage to variables that will not fall out of scope.
